# Generated by Django 4.2.2 on 2023-06-29 14:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4)),
                ('name', models.CharField(max_length=32)),
                ('post', models.CharField(choices=[('P', 'PGT'), ('T', 'TGT'), ('C', 'COACH')], default='T', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.SmallIntegerField()),
                ('p1', models.CharField(default='F', max_length=3)),
                ('p2', models.CharField(default='F', max_length=3)),
                ('p3', models.CharField(default='F', max_length=3)),
                ('p4', models.CharField(default='F', max_length=3)),
                ('p5', models.CharField(default='F', max_length=3)),
                ('p6', models.CharField(default='F', max_length=3)),
                ('p7', models.CharField(default='F', max_length=3)),
                ('p8', models.CharField(default='F', max_length=3)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Absent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('exempt', models.BooleanField(default=False)),
                ('s1', models.BooleanField(default=True)),
                ('s2', models.BooleanField(default=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.teacher')),
            ],
        ),
    ]
