# Generated by Django 4.2.2 on 2023-06-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('post', models.CharField(choices=[('P', 'PGT'), ('T', 'TGT')], default='T', max_length=1)),
                ('p1', models.CharField(max_length=3)),
                ('p2', models.CharField(max_length=3)),
                ('p3', models.CharField(max_length=3)),
                ('p4', models.CharField(max_length=3)),
                ('p5', models.CharField(max_length=3)),
                ('p6', models.CharField(max_length=3)),
                ('p7', models.CharField(max_length=3)),
                ('p8', models.CharField(max_length=3)),
            ],
        ),
    ]
