# Generated by Django 4.2.2 on 2023-06-24 12:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('59d1ea76-f9ce-41d5-9c97-007f245636bb'), unique=True),
        ),
    ]
