# Generated by Django 4.2.2 on 2023-06-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='sections',
            field=models.CharField(default='ABCDE', max_length=5),
        ),
    ]
