# Generated by Django 4.2.2 on 2023-06-24 13:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_teacher_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('26fb92ea-d7a5-4c94-b186-fe77ae44b83f'), unique=True),
        ),
    ]
