# Generated by Django 4.2.2 on 2023-06-24 15:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_teacher_uid_absent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='p1',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='p2',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='p3',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='p4',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='p5',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='p6',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='p7',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='p8',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('8fad208b-a26e-4d14-bbc7-8c2668ce252a'), unique=True),
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.SmallIntegerField()),
                ('p1', models.CharField(max_length=3)),
                ('p2', models.CharField(max_length=3)),
                ('p3', models.CharField(max_length=3)),
                ('p4', models.CharField(max_length=3)),
                ('p5', models.CharField(max_length=3)),
                ('p6', models.CharField(max_length=3)),
                ('p7', models.CharField(max_length=3)),
                ('p8', models.CharField(max_length=3)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.teacher')),
            ],
        ),
    ]
