# Generated by Django 4.2.2 on 2023-06-24 17:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_teacher_p1_remove_teacher_p2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('febdbb6b-1e08-4a8e-a41d-2ba4ee0cf39b'), unique=True),
        ),
    ]
