# Generated by Django 4.2.2 on 2023-06-25 13:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_teacher_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='p1',
            field=models.CharField(default='F', max_length=3),
        ),
        migrations.AlterField(
            model_name='table',
            name='p2',
            field=models.CharField(default='F', max_length=3),
        ),
        migrations.AlterField(
            model_name='table',
            name='p3',
            field=models.CharField(default='F', max_length=3),
        ),
        migrations.AlterField(
            model_name='table',
            name='p4',
            field=models.CharField(default='F', max_length=3),
        ),
        migrations.AlterField(
            model_name='table',
            name='p5',
            field=models.CharField(default='F', max_length=3),
        ),
        migrations.AlterField(
            model_name='table',
            name='p6',
            field=models.CharField(default='F', max_length=3),
        ),
        migrations.AlterField(
            model_name='table',
            name='p7',
            field=models.CharField(default='F', max_length=3),
        ),
        migrations.AlterField(
            model_name='table',
            name='p8',
            field=models.CharField(default='F', max_length=3),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('557030ff-7dd4-49be-8aa1-019e4eae69a9'), unique=True),
        ),
    ]
