# Generated by Django 4.2.2 on 2023-06-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_teacher_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='uid',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
