# Generated by Django 4.2.2 on 2023-06-27 12:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_teacher_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='absent',
            name='exempt',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
